controller_manager:
  ros__parameters:
    update_rate: 500 # Hz
    use_sim_time: true
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController

joint_group_position_controller:
  ros__parameters:
    # publish_rate: 50.0
    joints:
      - lh_hip_joint
      - lh_upper_leg_joint
      - lh_lower_leg_joint
      - lf_hip_joint
      - lf_upper_leg_joint
      - lf_lower_leg_joint
      - rf_hip_joint
      - rf_upper_leg_joint
      - rf_lower_leg_joint
      - rh_hip_joint
      - rh_upper_leg_joint
      - rh_lower_leg_joint
    command_interfaces:
      - position
    state_interfaces:
      - position