controller_manager:
  ros__parameters:
    update_rate: 50 # Frequency for updating controllers
    state_publish_rate: 50.0 # Frequency for publishing joint states
    use_sim_time: true # Use simulation time

    # List of controllers to load
    joint_state_broadcast:
      ros__parameters:
        type: joint_state_broadcaster/JointStateBroadcaster
        publish_rate: 50.0

    position_controller:
      ros__parameters:
        type: position_controllers/JointGroupPositionController
        publish_rate: 50.0
        joints:
          - joint_FLA
          - joint_FLB
          - joint_FLC
          - joint_FRA
          - joint_FRB
          - joint_FRC
          - joint_BLA
          - joint_BLB
          - joint_BLC
          - joint_BRA
          - joint_BRB
          - joint_BRC
        constraints:
          goal_time: 0.5
          stopped_velocity_tolerance: 0.05