controller_manager:
  ros__parameters:
    update_rate: 500 # Hz
    use_sim_time: true
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController

joint_group_position_controller:
  ros__parameters:
    publish_rate: 50.0
    joints:
      - joint_FLA
      - joint_FLB
      - joint_FLC
      - joint_FRA
      - joint_FRB
      - joint_FRC
      - joint_BLA
      - joint_BLB
      - joint_BLC
      - joint_BRA
      - joint_BRB
      - joint_BRC
    command_interfaces:
      - position
    state_interfaces:
      - position