controller_manager:
  ros__parameters:
    update_rate: 1  # Fréquence de mise à jour en Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    state_interfaces:
      - position

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_FLA
      - joint_FLB
      - joint_FLC
      - joint_FRA
      - joint_FRB
      - joint_FRC
      - joint_BLA
      - joint_BLB
      - joint_BLC
      - joint_BRA
      - joint_BRB
      - joint_BRC
    parameters:
      state_publish_rate: 50
      command_interfaces:
        - position
      interpolation_method: linear

