Panels:
  - Class: rviz_common/Displays
    Help Height: 70
    Name: Displays
    Property Tree Widget:
      Expanded:
        - /Global Options1
        - /Grid1
        - /Grid1/Status1
        - /TF1
      Splitter Ratio: 0.5
    Tree Height: 302
  - Class: rviz_common/Views
    Expanded:
      - /Current View1
      - /Current View1/Focal Point1
    Name: Views
    Splitter Ratio: 0.5
Visualization Manager:
  Class: ""
  Displays:
    - Alpha: 0.5
      Cell Size: 1
      Class: rviz_default_plugins/Grid
      Color: 160; 160; 164
      Enabled: true
      Line Style:
        Line Width: 0.029999999329447746
        Value: Lines
      Name: Grid
      Normal Cell Count: 0
      Offset:
        X: 0
        Y: 0
        Z: 0
      Plane: XY
      Plane Cell Count: 10
      Reference Frame: base_link
      Value: true
    - Alpha: 1
      Class: rviz_default_plugins/RobotModel
      Collision Enabled: false
      Description File: ""
      Description Source: Topic
      Description Topic:
        Depth: 5
        Durability Policy: Volatile
        History Policy: Keep Last
        Reliability Policy: Reliable
        Value: /robot_description
      Enabled: true
      Links:
        All Links Enabled: true
        BLA:
          Alpha: 1
          Show Axes: false
          Show Trail: false
          Value: true
        BLB:
          Alpha: 1
          Show Axes: false
          Show Trail: false
          Value: true
        BLC:
          Alpha: 1
          Show Axes: false
          Show Trail: false
          Value: true
        BRA:
          Alpha: 1
          Show Axes: false
          Show Trail: false
          Value: true
        BRB:
          Alpha: 1
          Show Axes: false
          Show Trail: false
          Value: true
        BRC:
          Alpha: 1
          Show Axes: false
          Show Trail: false
          Value: true
        Expand Joint Details: false
        Expand Link Details: false
        Expand Tree: false
        FLA:
          Alpha: 1
          Show Axes: false
          Show Trail: false
          Value: true
        FLB:
          Alpha: 1
          Show Axes: false
          Show Trail: false
          Value: true
        FLC:
          Alpha: 1
          Show Axes: false
          Show Trail: false
          Value: true
        FRA:
          Alpha: 1
          Show Axes: false
          Show Trail: false
          Value: true
        FRB:
          Alpha: 1
          Show Axes: false
          Show Trail: false
          Value: true
        FRC:
          Alpha: 1
          Show Axes: false
          Show Trail: false
          Value: true
        Link Tree Style: Links in Alphabetic Order
        base_link:
          Alpha: 1
          Show Axes: false
          Show Trail: false
          Value: true
      Mass Properties:
        Inertia: false
        Mass: false
      Name: RobotModel
      TF Prefix: ""
      Update Interval: 0
      Value: true
      Visual Enabled: true
    - Class: rviz_default_plugins/TF
      Enabled: true
      Filter (blacklist): ""
      Filter (whitelist): ""
      Frame Timeout: 15
      Frames:
        All Enabled: true
        BLA:
          Value: true
        BLB:
          Value: true
        BLC:
          Value: true
        BRA:
          Value: true
        BRB:
          Value: true
        BRC:
          Value: true
        FLA:
          Value: true
        FLB:
          Value: true
        FLC:
          Value: true
        FRA:
          Value: true
        FRB:
          Value: true
        FRC:
          Value: true
        base_link:
          Value: true
      Marker Scale: 0.10000000149011612
      Name: TF
      Show Arrows: true
      Show Axes: true
      Show Names: true
      Tree:
        base_link:
          BLA:
            BLB:
              BLC:
                {}
          BRA:
            BRB:
              BRC:
                {}
          FLA:
            FLB:
              FLC:
                {}
          FRA:
            FRB:
              FRC:
                {}
      Update Interval: 0
      Value: true
  Enabled: true
  Global Options:
    Background Color: 48; 48; 48
    Fixed Frame: base_link
    Frame Rate: 30
  Name: root
  Tools:
    - Class: rviz_default_plugins/MoveCamera
  Transformation:
    Current:
      Class: rviz_default_plugins/TF
  Value: true
  Views:
    Current:
      Class: rviz_default_plugins/Orbit
      Distance: 0.5836159586906433
      Enable Stereo Rendering:
        Stereo Eye Separation: 0.05999999865889549
        Stereo Focal Distance: 1
        Swap Stereo Eyes: false
        Value: false
      Focal Point:
        X: 0
        Y: 2.384185791015625e-07
        Z: 1.4901161193847656e-07
      Focal Shape Fixed Size: true
      Focal Shape Size: 0.05000000074505806
      Invert Z Axis: false
      Name: Current View
      Near Clip Distance: 0.009999999776482582
      Pitch: 0.34
      Target Frame: <Fixed Frame>
      Value: Orbit (rviz_default_plugins)
      Yaw: 2.22682
    Saved: ~
Window Geometry:
  Height: 800
  Width: 1200
